import Head from "next/head";
import { Inter } from "next/font/google";
import React, { useCallback, useMemo, useState } from "react";
import { Box, Button, Container, Stack, ThemeProvider } from "@mui/material";
import theme from "@/themes";
import Drawer from "@/components/componentsProva/Drawer";

const inter = Inter({ subsets: ["latin"] });

const Child = ({ id, onClick }) => {
  return <button onClick={() => onClick(id)}>Select Child {id}</button>;
};

const Parent = () => {
  const [selectedChild, setSelectedChild] = useState(null);
  const [count, setCount] = useState(0);

  const handleChildClick = useCallback((childId) => {
    setSelectedChild(childId);
  }, []);

  /*
  const handleClick = (childId) => {
    setSelectedChild(childId);
  };
*/

  const label = useMemo(() => {
    let num = 5;

    for (let i = 0; i < 1000000000; i++) {
      num += i;
    }
    return num;
  }, []);

  const handleAdd = () => {
    setCount((prev) => prev + 1);
  };

  return (
    <div>
      <h2>Parent Component</h2>
      {selectedChild && <p>Child {selectedChild} selected!</p>}
      <Child id={1} onClick={handleChildClick} />
      <Child id={2} onClick={handleChildClick} />
      <Child id={3} onClick={handleChildClick} />
      <button onClick={handleAdd}>{count}</button>
    </div>
  );
};

export default function Home() {
  const handleClick = () => {
    console.log("Button clicked in parent");
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Parent />
      <div>Hello world!</div>
      <ThemeProvider theme={theme}>
        <Stack spacing={2} direction="row" justifyContent="center">
          <Box>
            <Button
              sx={{ flex: 2 }}
              children={"Hello World"}
              variant={"contained"}
              onClick={() => alert("Hello World")}
            />
          </Box>
          <Box sx={{ bgcolor: "primary.main" }}>ciao</Box>
          <Box>
            <Button
              sx={{ flex: 1 }}
              children={"Hello World"}
              variant={"outlined"}
            />
          </Box>
          <Drawer />
        </Stack>
        <Container></Container>
      </ThemeProvider>
    </>
  );
}
